### ISSUE TITLE
Update for Xcode 6 ios8? Better instructions?

### ISSUE THREAD

**Issue by benjaminhallock** [appcornerit/DeploydKit#12]
I'm trying to add this to my project, and while I believe I did it correctly, all I get is a ton of bugs with autorelease and old objective depreciated. 

I need to know if this is supported anymore, because it just doesn't work.

**Comment by appcornerit** [comment]
Apologies for my delayed response, this project is no longer being maintained. However you could try the code released here:
https://github.com/appcornerit/AppCorner-Social/tree/master/External/DeploydKit
